-- MySQL Script generated by MySQL Workbench
-- Wed Apr 27 15:14:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TwitterClone
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TwitterClone
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TwitterClone` DEFAULT CHARACTER SET utf8 ;
USE `TwitterClone` ;

-- -----------------------------------------------------
-- Table `TwitterClone`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TwitterClone`.`User` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `IsAdmin` TINYINT NULL,
  PRIMARY KEY (`UserId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TwitterClone`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TwitterClone`.`Post` (
  `PostID` INT NOT NULL AUTO_INCREMENT,
  `PostText` VARCHAR(45) NOT NULL,
  `Likes` INT NOT NULL,
  `Timestamp` DATETIME NOT NULL,
  `UserId` INT NOT NULL,
  `flagged` TINYINT NULL,
  PRIMARY KEY (`PostID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TwitterClone`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TwitterClone`.`Comment` (
  `CommentId` INT NOT NULL AUTO_INCREMENT,
  `Text` VARCHAR(45) NOT NULL,
  `PostId` INT NOT NULL,
  `UserId` INT NOT NULL,
  PRIMARY KEY (`CommentId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TwitterClone`.`Follows`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TwitterClone`.`Follows` (
  `User1Id` INT NOT NULL,
  `User2Id` INT NOT NULL,
  PRIMARY KEY (`User1Id`, `User2Id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';